"""
test_appendix_g_regression.py
===============================

Automated regression suite for cudal's acceptance-limit calculations,
tied directly to the Validation Protocol's Appendix G (Program Test Data
Sets).

What this is
-------------
This is the CI-enforced counterpart to Form 4 (Test Data Agreement) in the
Validation Protocol. Form 4 is executed by a human, once, as part of formal
validation. This suite runs the *same* input parameters through cudal on
every commit / pull request, and asserts the output still matches a frozen
set of reference values -- so a future code change can never silently
change the math without a test failing.

What this is NOT
------------------
This is not an independent verification of correctness by itself. The
frozen reference values in tests/data/*.json were generated by cudal's own
functions (see generate_reference_data.py) at a point in time when those
functions had already been independently verified by other means:
  - line-by-line comparison against the original SAS macros,
  - an independent R re-implementation cross-checked against the same
    Appendix G inputs (see the User Manual / Annexure),
  - the CUSP2 Discrepancy Investigation, which confirmed cudal's CUSP2
    boundary search converges to the mathematically correct root.

In other words: correctness was established elsewhere. This suite's job is
narrower and simpler -- make sure it stays that way.

Updating the reference values
-------------------------------
If a deliberate, reviewed change to the math ever requires updating the
frozen values, regenerate them with generate_reference_data.py and say so
explicitly in the commit message and PR description, with a reference to
whatever re-verification was performed. Do not regenerate them just to
make a failing test pass -- that defeats the purpose of this suite.
"""

import json
import math
from pathlib import Path

import pytest

from cudal import cusp1, cusp2

DATA_DIR = Path(__file__).resolve().parent / "data"

# Tolerances are deliberately tight: these are root-finding results, not
# measurements, so run-to-run reproducibility should be near machine
# precision. 1e-4 comfortably covers solver/platform noise while still
# catching any real change in behavior.
CV_TOL = 1e-4
MEAN_TOL = 1e-4


def _load(name):
    with open(DATA_DIR / name) as f:
        return json.load(f)


CUSP1_CASES = _load("cusp1_appendix_g.json")
CUSP2_CASES = _load("cusp2_appendix_g.json")


def _case_id_cusp1(case):
    return f"N{case['number']}_T{case['target']}_LB{case['lbound']}_CI{case['cilevel']}_M{case['mean']}"


def _case_id_cusp2(case):
    return f"L{case['loc']}_U{case['perloc']}_T{case['target']}_LB{case['lbound']}_CI{case['cilevel']}_SE{case['se']}_SM{case['sm']}"


# ===========================================================================
# CUSP1 -- Content Uniformity, Sampling Plan 1  (Appendix G, Section G.1)
# ===========================================================================

@pytest.mark.parametrize("case", CUSP1_CASES, ids=[_case_id_cusp1(c) for c in CUSP1_CASES])
def test_cusp1_acceptance_limit_matches_appendix_g(case):
    """
    Each case is one row of Appendix G, Section G.1: a (Sample Size, Target,
    Lower Bound, CI Level) group evaluated at one of its three Sample Mean
    values. Rebuilds the single-mean acceptance-limit table and checks the
    resulting CV against the frozen reference value.
    """
    table = cusp1.acceptance_limit_table(
        number=case["number"],
        target=case["target"],
        lbound=case["lbound"],
        cilevel=case["cilevel"],
        mean_low=case["mean"],
        mean_high=case["mean"],
        mean_step=1.0,  # single point; mean_low == mean_high
    )
    assert len(table) == 1
    actual_cv = float(table["CV"].iloc[0])

    assert actual_cv == pytest.approx(case["expected_cv"], abs=CV_TOL), (
        f"CUSP1 CV mismatch for N={case['number']}, target={case['target']}, "
        f"lbound={case['lbound']}, cilevel={case['cilevel']}, mean={case['mean']}: "
        f"expected {case['expected_cv']}, got {actual_cv}"
    )


# ===========================================================================
# CUSP2 -- Content Uniformity, Sampling Plan 2  (Appendix G, Section G.2)
# ===========================================================================

@pytest.mark.parametrize("case", CUSP2_CASES, ids=[_case_id_cusp2(c) for c in CUSP2_CASES])
def test_cusp2_acceptance_limit_matches_appendix_g(case):
    """
    Each case is one (Location, Units/Location, Target, Lower Bound, CI
    Level, SE, SM) combination from Appendix G, Section G.2. Checks both
    MEANL and MEANU against frozen reference values, including the
    NaN ("no acceptable mean range exists") cases.
    """
    table = cusp2.acceptance_limit_table(
        num=case["perloc"],
        loc=case["loc"],
        target=case["target"],
        lbound=case["lbound"],
        cilevel=case["cilevel"],
        se_values=[case["se"]],
        sm_values=[case["sm"]],
    )
    assert len(table) == 1
    actual_meanl = table["MEANL"].iloc[0]
    actual_meanu = table["MEANU"].iloc[0]

    expected_meanl = case["expected_meanl"]
    expected_meanu = case["expected_meanu"]

    if expected_meanl is None:
        assert actual_meanl != actual_meanl, (  # NaN check without numpy import
            f"Expected MEANL to be NaN (no acceptable mean range) for "
            f"loc={case['loc']}, units/loc={case['perloc']}, target={case['target']}, "
            f"lbound={case['lbound']}, cilevel={case['cilevel']}, se={case['se']}, sm={case['sm']}, "
            f"but got {actual_meanl}"
        )
    else:
        assert float(actual_meanl) == pytest.approx(expected_meanl, abs=MEAN_TOL), (
            f"CUSP2 MEANL mismatch for loc={case['loc']}, units/loc={case['perloc']}, "
            f"target={case['target']}, lbound={case['lbound']}, cilevel={case['cilevel']}, "
            f"se={case['se']}, sm={case['sm']}: expected {expected_meanl}, got {actual_meanl}"
        )

    if expected_meanu is None:
        assert actual_meanu != actual_meanu, (
            f"Expected MEANU to be NaN (no acceptable mean range) for "
            f"loc={case['loc']}, units/loc={case['perloc']}, target={case['target']}, "
            f"lbound={case['lbound']}, cilevel={case['cilevel']}, se={case['se']}, sm={case['sm']}, "
            f"but got {actual_meanu}"
        )
    else:
        assert float(actual_meanu) == pytest.approx(expected_meanu, abs=MEAN_TOL), (
            f"CUSP2 MEANU mismatch for loc={case['loc']}, units/loc={case['perloc']}, "
            f"target={case['target']}, lbound={case['lbound']}, cilevel={case['cilevel']}, "
            f"se={case['se']}, sm={case['sm']}: expected {expected_meanu}, got {actual_meanu}"
        )


# ===========================================================================
# Sanity checks on the reference data itself
# ===========================================================================

def test_reference_data_row_counts():
    """Guards against someone accidentally truncating or duplicating the
    frozen reference files themselves."""
    assert len(CUSP1_CASES) == 36, "Appendix G, Section G.1 has 36 rows"
    assert len(CUSP2_CASES) == 50, "Appendix G, Section G.2 has 50 rows"


def test_reference_data_cusp2_known_exclusions_absent():
    """The two (SE, SM) combinations documented as excluded in Appendix G
    (Location=3, Units/Location=2, Target=100.0, Lower Bound=99.0,
    CI Level=99.0) should never reappear in the frozen data."""
    excluded = {(0.1, 3.0), (3.0, 0.1)}
    for case in CUSP2_CASES:
        if (case["loc"], case["perloc"], case["target"], case["lbound"], case["cilevel"]) == (
            3, 2, 100.0, 99.0, 99.0
        ):
            assert (case["se"], case["sm"]) not in excluded
